### ISSUE TITLE
Crash with Lantern - 

### ISSUE THREAD

**Issue by rckymtnrfc** [InfinityRaider/BoatLantern#2]
I'm seeing the following crash on the server with boatlantern-0.2 and infinityLib-0.2.  Goes away if I pull out Lantern and leave InfinityLib.

http://pastebin.com/fANmZSUd

Thanks!

**Comment by Ravin890** [comment]
I used it earlier and no issues which is strange.
(Different mods in mod folder though)

**Comment by rckymtnrfc** [comment]
Ravin890,, are you running it on a server?  I believe that is the issue.  The mod is making a rendering call that should not happen on the server.  And yes, 0.2.

**Comment by Ravin890** [comment]
Server is a nope XD

**Comment by InfinityRaider** [comment]
Dang, forgot to test server before release. 
I forgot a SideOnly(Side.CLIENT) annotation somewhere, tx for reporting.

**Comment by InfinityRaider** [comment]
This one line :s
https://github.com/InfinityRaider/BoatLantern/commit/c9d5e4ba195d2ddcee864409eb24a56522ed981f#diff-3770c45398996920faa6c1eef3ce8390R79
