### ISSUE TITLE
Modname vs filename and library

### ISSUE THREAD

**Issue by xenoflot** [InfinityRaider/BoatLantern#5]
Hi,

Just a couple of small suggestions.

At the moment there's a discrepancy between the mod name and the file name. For those of us that use an automated mod manager, it would be helpful if they were the same.

Also I note that on Curseforge, your info page for Lantern doesn't mention that a library is needed. It'd be helpful if you included a link to the library project.

Cheers!

**Comment by InfinityRaider** [comment]
That the modname and filename are different seems trivial for me, I'm sorry but all my mods will and always have the same filename as the mod id. The fact that it started of as boatlantern is that originally it was mainly a lantern for a boat, but the functionality is a lot more than that, therefore I chose to name it lantern.

And as far as I am aware the dependency is properly up on CurseForge:
https://i.gyazo.com/983309fdeffc0c19df71729ad774fb7d.png
