### ISSUE TITLE
Exception in Server Tick Loop Crash

### ISSUE THREAD

**Issue by WenXin20** [InfinityRaider/BoatLantern#7]
Forge 2151-Client
Boat Lantern v2.1
I had a lantern in my hot bar when I crashed. Not sure if this had anything to do with it, but I was also right-clicking on a horse to tame it and it kicked me off then the game crashed.

**Comment by InfinityRaider** [comment]
Crash log?

**Comment by WenXin20** [comment]
Sorry, forgot to include it :D 
[Crash Log ](http://pastebin.com/fANmZSUd)

**Comment by InfinityRaider** [comment]
wtf is that crash o.O...
I'm clueless

**Comment by InfinityRaider** [comment]
InfinityLIb will be updated in the next release, if it still happens, feel free to repoen this

**Comment by WenXin20** [comment]
Ok
